# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
