# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('ip', models.CharField(default='1.1.1.1', max_length=32)),
                ('depart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myweb.Department')),
            ],
        ),
    ]
