# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_hosts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosts',
            old_name='depart',
            new_name='depart_id',
        ),
    ]
